/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zzl_bestidear_wifidirect_miracast_SinkPlayer */

#ifndef _Included_zzl_bestidear_wifidirect_miracast_SinkPlayer
#define _Included_zzl_bestidear_wifidirect_miracast_SinkPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zzl_bestidear_wifidirect_miracast_SinkPlayer
 * Method:    setRtspSink
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_zzl_bestidear_wifidirect_miracast_SinkPlayer_setRtspSink
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     zzl_bestidear_wifidirect_miracast_SinkPlayer
 * Method:    stopRtspSink
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zzl_bestidear_wifidirect_miracast_SinkPlayer_stopRtspSink
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
